volumes:
  sqlserver_data1:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - .env
    user: root
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data1:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 1a0be1b1-e6b5-4c02-ba11-7c0520804c9c -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
  init-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      bash -c "
      /opt/mssql-tools18/bin/sqlcmd 
      -S sqlserver 
      -U sa 
      -P ${MSSQL_SA_PASSWORD} 
      -C 
      -d master 
      -i docker-entrypoint-initdb.d/init-db.sql 
      -v DB_NAME='${DB_NAME}' DB_USER='${DB_USER}' DB_USER_PASSWORD='${DB_USER_PASSWORD}' ;
      echo 'All done!';
      "